import {
   COMMUTE_DASHBOARD_PREFIX,
   COMMUTE_DASHBOARD_HOME_PAGE,
   COMMUTE_DASHBOARD_MATCHEDRESULTS
} from '../../Commute/constants/NavigationalConstants'
export const COMMUTE_DASHBOARD_SIGNUP_PAGE:string = `${COMMUTE_DASHBOARD_PREFIX}/signin`
export const COMMUTE_DASHBOARD_LOGIN_PAGE:string = `${COMMUTE_DASHBOARD_PREFIX}/login`
export { COMMUTE_DASHBOARD_HOME_PAGE, COMMUTE_DASHBOARD_MATCHEDRESULTS }
